# baseURL should be
# "https://YOUR-GITHUB-USERNAME.github.io/lean-site-template/" during development,
# and "your-ea-domain.org/" after your domain has been set up.
baseURL = "https://eatuebingen.github.io/lean-site-template/"
theme = "local-ea-template"
canonifyURLs = true

# If you are using multiple languages and want a different default,
# you can change this language code. In this particular case,
# baseURL will be the English site, and baseURL/<language code> will be the
# other languages.
DefaultContentLanguage = "de"

# These params are used by the local EA Hugo template
# used to generate the site. You can find the template
# at https://github.com/rtcharity/local-ea-template.
  [params]

  [Languages]
  [Languages.en]
  title = "EA Tübingen"
  weight = 1
  languageCode = "de"

  [Languages.en.general]
  ## -- GENERAL SITE PARAMETERS -- ##
  fullTitle = "Effektiver Altruismus - Tübingen"
  strapline = "GUTES BESSER TUN"

  [Languages.en.groupinfo]
  ## -- EA GROUP INFO -- ##
  legalOrgName = "Effektiver Altruismus Tübingen"
  orgLocations = ""
  contactEmail = "jonathan.oesterle@web.de"

  [Languages.en.navbar]
  ## -- NAVIGATION BAR HEADERS -- ##
  # You probably don't need/want to change these,
  # but if you do you'll also want to change the relevant .md file under the
  # content folder so the copy corresponds with the header.
  home = "Home"
  faq = "FAQ"
  effectiveAltruism = "Effektiver Altruismus"
  aboutEA = "About EA"
  readingMaterial = "Reading Material"
  keyTerms = "Key Terms"
  organizations = "Organizations"
  contact= "Contact"

  [Languages.en.pages]
  ## -- PAGE HEADERS -- ##
  contactPageHeader = "Contact us"
  aboutEAPageHeader = "What is Effective Altruism?"

  [Languages.en.homepage]
   ## -- HOMEPAGE -- ##
  topBannerText = "Wer wir sind?"
  leadText = "Wir sind eine Gruppe von Leuten die Dir dabei helfen wollen die Frage zu beantworten: wie kann ich Gutes besser tun?"
  firstSectionHeader = "Gutes besser tun"
  secondSectionHeader = "Eine Community aufbauen"
  thirdSectionHeader = "Besser Wege finden um zu helfen"
  bottomBannerText = "Stolze Mitglieder des Effective Altruism Netzwerks"

  [Languages.en.contactform]
  ## -- CONTACT FORM -- ##
  leadText = "Say hi!"
  senderName = "Your name (required)"
  senderEmail = "Your email (required)"
  emailSubject = "Subject"
  emailMessage = "Your Message"
  send = "Send"

  [Languages.en.jumbotron]
  # These are the buttons right under the header that appears on the main page.
  # You can use them to link to a mailing list or Facebook page.
  # Make sure the links start with http:// or https://
  firstButtonText = "First Button Text"
  firstButtonLink = ""
  secondButtonText = "Second Button Text"
  secondButtonLink = ""
  # Remove the # before the text to add the optional Meetup button
  # meetupButtonText = "Find us on Meetup"

  [Languages.en.urls]
  ## -- EA GROUP FB/TWITTER/MEETUP URLS -- ##
  # If your group does not have URLs for these, just add # before the line
  # to remove the link from the site
  facebookUrl = ""
  twitterUrl = ""
  meetupUrl = ""
