baseURL = "https://eatuebingen.github.io/lean-site-template/"
theme = "local-ea-template"

DefaultContentLanguage = "de"

  [params]

  [Languages]
  [Languages.en]
  languageCode = "en"
  title = "Local EA Website"
  weight = 1

  [Languages.en.general]
  ## -- GENERAL SITE PARAMETERS -- ##
  fullTitle = "EA Is Awesome"
  strapline = "Helping you do good better"

  ## -- EA GROUP INFO -- ##
  [Languages.en.groupinfo]
  legalOrgName = "Effective Altruism Tübingen"
  orgLocations = "Germany"
  registeredCharityNumber = ""
  contactEmail = "jonathan.oesterle@web.de"

  [Languages.en.navbar]
  ## -- NAVIGATION BAR HEADERS -- ##
  home = "Home"
  faq = "FAQ"
  effectiveAltruism = "Effective Altruism"
  aboutEA = "About EA"
  readingMaterial = "Reading Material"
  keyTerms = "Key Terms"
  organizations = "Organizations"
  contact= "Contact"

  [Languages.en.pages]
  ## -- PAGES HEADERS-- ##
  aboutPageHeader = "About us"
  contactPageHeader = "Contact us"
  aboutEAPageHeader = "What is Effective Altruism?"

  [Languages.en.homepage]
   ## -- HOMEPAGE -- ##
  topBannerText = "Who are we?"
  leadText = "We're a group of people who want to help you answer the question: how can I do good better?"
  firstSectionHeader = "Doing good better"
  secondSectionHeader = "Building a community"
  thirdSectionHeader = "Finding better ways to help"
  bottomBannerText = "A proud member of the effective altruism network"

  [Languages.en.contactform]
    ## -- CONTACT FORM -- ##
  leadText = "Say hi!"
  senderName = "Your name (required)"
  senderEmail = "Your email (required)"
  emailSubject = "Subject"
  emailMessage = "Your Message:"
  send = "Send"

  [Languages.en.jumbotron]
  firstButtonText = "Follow our mailing list"
  firstButtonLink = "http://www.mailinglist.link/12345"
  secondButtonText = "Join us on Facebook"
  secondButtonLink = "http://www.facebook.com/someEAFacebookGroup"
  meetupButtonText = "Find us on Meetup"

  [Languages.en.urls]
  ## -- EA GROUP FB/TWITTER/MEETUP URLS -- ##
  facebookUrl = "https://www.facebook.com/EATuebingen/"
  #twitterUrl = ""
  #meetupUrl = ""


  [Languages.de]
  languageCode = "de"
  title = "EA Tübingen"
  weight = 2

  [Languages.de.general]
  fullTitle = "Effektiver Alltrusimus"
  strapline = "Habe ich nicht schon gesagt, dass EA ist das Beste?!"

  [Languages.de.groupinfo]
  legalOrgName = "Effektiver Altruismus Tübingen"
  orgLocations = "Germany"
  registeredCharityNumber = ""
  contactEmail = "jonathan.oesterle@web.de"

  [Languages.de.navbar]
  home = "Home"
  faq = "FAQ"
  effectiveAltruism = "Effektiver Altruismus"
  aboutEA = "Über EA"
  readingMaterial = "Lesestoff"
  keyTerms = "Wortliste"
  organizations = "Organisationen"
  contact= "Kontakte"

  [Languages.de.pages]
  contactPageHeader = "Wenden Sie sich an uns"
  aboutEAPageHeader = "Was ist Effektiven Altruismus?"

  [Languages.de.homepage]
  topBannerText = "Wer sind wir?"
  leadText = "Wir sind eine Gruppe von Leuten die dabei helfen wollen die Frage zu beantworten: wie können wir Gutes besser und effektiver tun?"
  firstSectionHeader = "Gutes besser tun"
  secondSectionHeader = "Eine Community aufbauen"
  thirdSectionHeader = "Bessere Wege finden zu helfen"
  bottomBannerText = "Mitglieder des Effective Altruism Netzwerks"

  [Languages.de.contactform]
  leadText = "Sagen Sie Hallo!"
  senderName = "Deine Name(required)"
  senderEmail = "Dein Email (required)"
  emailSubject = "Subjekt"
  emailMessage = "Deine Nachricht:"
  send = "Schicken"

  [Languages.de.jumbotron]
  firstButtonText = ""
  firstButtonLink = ""
  secondButtonText = "Besuche uns auf Facebook"
  secondButtonLink = "https://www.facebook.com/EATuebingen/"
  meetupButtonText = "Finden Sie uns auf Meetup"

  [Languages.de.urls]
  facebookUrl = "http://www.facebook.com/someEAFacebookGroup"
  #twitterUrl = ""
  #meetupUrl = ""
